# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fairphone/FP2/setup-makefiles.sh

ifeq ($(WITH_TWRP),true)
TARGET_RECOVERY_DEVICE_DIRS += vendor/fairphone/FP2/proprietary
endif
